version: 2.1

executors:
  ubuntu-machine-executor:
    machine:
      image: ubuntu-2204:2023.07.2
      docker_layer_caching: true


jobs:
  build:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            # log in to docker
            echo $DOCKER_API_KEY | docker login -u mt9399 --password-stdin
            docker build -f app.Dockerfile -t app .
            docker tag app mt9399/app:latest
            docker push mt9399/app:latest
  test:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker pull mt9399/app:latest
            docker run --rm app

  bump_version:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Install semantic-release
          command: |
            # install python3 and pip
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            # install semantic-release
            pip3 install python-semantic-release==8.1.1
            semantic-release --version
      - run:
          name: Bump version
          command: |
            semantic-release version
            sleep 2

  tag_image:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Push image
          command: |
            export GH_VERSION=$(semantic-release version --print)
            echo $DOCKER_API_KEY | docker login -u mt9399 --password-stdin
            docker pull mt9399/app:latest
            docker tag mt9399/app:latest mt9399/app:$GH_VERSION
            docker push mt9399/app:$GH_VERSION


workflows:
  build_test_push:
    jobs:
      - build:
          context:
            - udp-server
            - docker
            - github
            - google
      - test:
          requires:
            - build
          context:
            - udp-server
            - docker
            - github
            - google
      - bump_version:
          requires:
            - test
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - main
                - dev
      - tag_image:
          requires:
            - bump_version
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - main
                - dev
