version: 2.1

executors:
  ubuntu-machine-executor:
    machine:
      image: ubuntu-2204:2023.07.2
      docker_layer_caching: true


jobs:
  build:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Exit on certain commit messages
          command: |
            export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
            # Exit if commit message starts with the word "merge" or "Merge" or is a version number like 3.0.25 or 3.0.25-dev.1
            if [[ $COMMIT_MESSAGE =~ ^[Mm]erge ]]; then
                echo "Commit message starts with the word 'merge'. Exiting job."
                echo "Commit message:"
                echo $COMMIT_MESSAGE
                exit 20
            fi
            if [[ $COMMIT_MESSAGE =~ ^[0-9]+\.[0-9]+\.[0-9]+(\n|.)*$ ]]; then
                echo "Commit message is a version number. Exiting job."
                echo "Commit message:"
                echo $COMMIT_MESSAGE
                exit 21
            fi
            if [[ $COMMIT_MESSAGE =~ ^[0-9]+\.[0-9]+\.[0-9]+-dev\.[0-9]+(\n|.)*$ ]]; then
                echo "Commit message is a dev version number. Exiting job."
                echo "Commit message:"
                echo $COMMIT_MESSAGE
                exit 22
            fi
            # continue with the rest of the job
      - run:
          name: Build image
          command: |
            # log in to docker
            echo $DOCKER_API_KEY | docker login -u mt9399 --password-stdin
            docker build -f app.Dockerfile -t app .
            docker tag app mt9399/app:latest
            docker push mt9399/app:latest

  test:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker pull mt9399/app:latest
            docker run --rm app

  bump_version:
    docker:
      - image: cimg/python:3.11
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Install git and semantic-release
          command: |
            pip install python-semantic-release==8.1.1
            semantic-release --version
      - run:
          name: Bump version
          command: |
            semantic-release version --no-commit --no-changelog --skip-build --push
            export GH_VERSION=v$(semantic-release version --print)
            git tag $GH_VERSION
            sleep 2

  tag_dev_image:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Install python3 and semantic-release
          command: |
            sudo apt-get update
            sudo apt-get install python3 python3-pip -y
            pip3 install python-semantic-release==8.1.1
            semantic-release --version
            sleep 2
      - run:
          name: Push image
          command: |
            # Put a v in front of version like v1.0.0 
            export GH_VERSION=v$(semantic-release version --print)  
            # Exit if this version is not a dev version
            if [[ $GH_VERSION != *"dev"* ]]; then
              echo "$GH_VERSION is not a dev version. Skipping image push."
              exit 0
            fi
            # Exit if an image with this same tag already exists
            echo $DOCKER_API_KEY | docker login -u mt9399 --password-stdin
            if docker pull mt9399/app:$GH_VERSION; then
              echo "Image with ($GH_VERSION) tag already exists. Skipping image push."
              exit 0
            fi
            # Tag the dev image
            docker pull mt9399/app:latest
            docker tag mt9399/app:latest mt9399/app:$GH_VERSION
            docker push mt9399/app:$GH_VERSION

  tag_prod_image:
    executor: ubuntu-machine-executor
    working_directory: /home/circleci/semrelease
    steps:
      - checkout
      - run:
          name: Install python3 and semantic-release
          command: |
            sudo apt-get update
            sudo apt-get install python3 python3-pip -y
            pip3 install python-semantic-release==8.1.1
            semantic-release --version
            sleep 2
      - run:
          name: Push image
          command: |
            # Put a v in front of version like v1.0.0 
            export GH_VERSION=v$(semantic-release version --print)  
            # Exit if this version is not a production release version that follows semantic versioning
            if [[ $GH_VERSION == *"dev"* ]]; then
              echo "$GH_VERSION is not a production release version. Skipping image push."
              exit 0
            fi
            # Exit if an image with this same tag already exists
            echo $DOCKER_API_KEY | docker login -u mt9399 --password-stdin
            if docker pull mt9399/app:$GH_VERSION; then
              echo "Image with ($GH_VERSION) tag already exists. Skipping image push."
              exit 0
            fi
            # Tag the dev image
            docker pull mt9399/app:latest
            docker tag mt9399/app:latest mt9399/app:$GH_VERSION
            docker push mt9399/app:$GH_VERSION


workflows:
  build_test_push_dev:
    jobs:
      - build:
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - dev
      - test:
          requires:
            - build
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              ignore:
                - main
      - bump_version:
          requires:
            - test
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - dev
      - tag_dev_image:
          requires:
            - bump_version
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - dev
  build_push_prod:
    # Don't run when commit message is a version number like 1.2.3
    jobs:
      - build:
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - main
      - bump_version:
          requires:
            - build
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - main
      - tag_prod_image:
          requires:
            - bump_version
          context:
            - udp-server
            - docker
            - github
            - google
          filters:
            branches:
              only:
                - main
                